
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F7F2',
  },
  header: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5EAE3',
  },
  headerButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#F0F5EF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerArrow: {
    color: '#176B4D',
    fontSize: 32,
    lineHeight: 36,
  },
  refreshIcon: {
    color: '#176B4D',
    fontSize: 27,
  },
  headerText: {
    flex: 1,
    marginHorizontal: 12,
  },
  eyebrow: {
    color: '#668074',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  headerTitle: {
    color: '#172820',
    fontSize: 18,
    fontWeight: '800',
  },
  content: {
    padding: 16,
    paddingBottom: 36,
  },
  heroCard: {
    backgroundColor: '#176B4D',
    borderRadius: 24,
    padding: 22,
    marginBottom: 16,
  },
  eyebrowLight: {
    color: '#C8E7D5',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  reference: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '900',
    marginTop: 10,
    marginBottom: 18,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  badge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '800',
  },
  heroFootnote: {
    color: '#D8EBE0',
    fontSize: 12,
    marginTop: 18,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5EAE3',
    padding: 18,
    marginBottom: 14,
  },
  sectionTitle: {
    color: '#172820',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 14,
  },
  issueTitle: {
    color: '#1A3025',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 10,
  },
  description: {
    color: '#526158',
    fontSize: 14,
    lineHeight: 22,
  },
  categoryPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#E5F2E9',
    borderRadius: 10,
    paddingHorizontal: 11,
    paddingVertical: 7,
    marginTop: 16,
  },
  categoryText: {
    color: '#176B4D',
    fontSize: 12,
    fontWeight: '800',
  },
  studentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: '#DDF0E4',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#176B4D',
    fontSize: 20,
    fontWeight: '900',
  },
  studentIdentity: {
    flex: 1,
  },
  studentName: {
    color: '#172820',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  muted: {
    color: '#77847B',
    fontSize: 13,
    lineHeight: 20,
  },
  infoRow: {
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#EEF1EC',
  },
  infoLabel: {
    color: '#77847B',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 5,
  },
  infoValue: {
    color: '#24392D',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  issuePhoto: {
    width: '100%',
    height: 230,
    borderRadius: 14,
    backgroundColor: '#E9EEE7',
  },
  actionCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CFE4D4',
    borderRadius: 22,
    padding: 18,
    marginBottom: 14,
  },
  actionDescription: {
    color: '#647168',
    fontSize: 13,
    lineHeight: 21,
    marginBottom: 18,
  },
  inputLabel: {
    color: '#26392D',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 9,
  },
  noteInput: {
    minHeight: 120,
    maxHeight: 220,
    borderWidth: 1,
    borderColor: '#DCE5DC',
    borderRadius: 14,
    backgroundColor: '#FBFCFA',
    padding: 14,
    color: '#172820',
    fontSize: 14,
    lineHeight: 21,
  },
  characterCount: {
    color: '#8A968E',
    fontSize: 11,
    textAlign: 'right',
    marginTop: 7,
    marginBottom: 14,
  },
  primaryButton: {
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#176B4D',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  disabledButton: {
    opacity: 0.65,
  },
  actionHint: {
    color: '#77847B',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 12,
  },
  completedCard: {
    backgroundColor: '#E7F5EC',
    borderColor: '#CBE7D4',
    borderWidth: 1,
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
    gap: 8,
  },
  completedTitle: {
    color: '#176B4D',
    fontSize: 16,
    fontWeight: '900',
  },
  timelineHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  timelineCount: {
    color: '#668074',
    fontSize: 11,
    fontWeight: '800',
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingTop: 15,
  },
  timelineDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
    marginTop: 5,
    marginRight: 12,
  },
  timelineBody: {
    flex: 1,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF1EC',
  },
  timelineStatus: {
    color: '#24392D',
    fontSize: 14,
    fontWeight: '800',
  },
  timelineDate: {
    color: '#88938B',
    fontSize: 11,
    marginTop: 5,
  },
  timelineNote: {
    color: '#526158',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 8,
  },
  timelineAuthor: {
    color: '#176B4D',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 7,
  },
  footer: {
    color: '#89958C',
    fontSize: 11,
    textAlign: 'center',
    lineHeight: 18,
    marginTop: 8,
    paddingHorizontal: 12,
  },
  centerState: {
    flex: 1,
    padding: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerTitle: {
    color: '#172820',
    fontSize: 19,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 8,
  },
  errorIcon: {
    color: '#B83232',
    backgroundColor: '#FCE6E6',
    width: 54,
    height: 54,
    borderRadius: 27,
    textAlign: 'center',
    textAlignVertical: 'center',
    overflow: 'hidden',
    fontSize: 28,
    fontWeight: '900',
  },
  backButton: {
    padding: 14,
    marginTop: 8,
  },
  backButtonText: {
    color: '#176B4D',
    fontSize: 14,
    fontWeight: '800',
  },
});

export default styles;
